default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER']%>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

# Use sqlite in production by default. Greenlight supports
production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite3' %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT' || '5432'] %>
  database: <%= ENV['DB_NAME'] || 'db/production/production.sqlite3' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
